### ISSUE TITLE
No Access to Logo

### ISSUE THREAD

**Issue by GeorgLink** [electric-capital/crypto-ecosystems#1057]
The [README](https://github.com/electric-capital/crypto-ecosystems#how-to-give-attribution-for-usage-of-the-electric-capital-crypto-ecosystems) has a "[Link to logo](https://drive.google.com/file/d/1DAX6wmcbtia7kaP5AaUWyg6t-ZEW9z22/view?usp=sharing)" - however, it leads to a Google Drive file that is not publicly viewable.

**Comment by GeorgLink** [comment]
Hi @eherrerosj , unfortunately, this issue is not completed because the link to the log still leads to an "access denied" google drive page.

Here's the reference to the line in the README: https://github.com/electric-capital/crypto-ecosystems/blob/f0274eda1607f1e8c42fc9511765da4df28ffbfd/README.md?plain=1#L71

**Comment by eherrerosj** [comment]
We are checking the issue, thanks @GeorgLink

**Comment by eherrerosj** [comment]
Should now be fixed @GeorgLink, thanks for pointing it out

**Comment by GeorgLink** [comment]
Confirmed, it's fixed. Thanks, @eherrerosj
