### ISSUE TITLE
CI Job is failing with "The remote provider was unable to process the request" error

### ISSUE THREAD

**Issue by gregzaitsev** [electric-capital/crypto-ecosystems#129]
##[warning]An image label with the label ubuntu-16.04 does not exist.
,##[error]The remote provider was unable to process the request.
Started: Today at 3:51 PM
Duration: 3m 34s

**Comment by gregzaitsev** [comment]
Hi! I'm just trying to make a new PR for Unique Network :)

**Comment by jubos** [comment]
Think this is fine now.
