### ISSUE TITLE
Merging Polkadot and Kusama ecosystem count together

### ISSUE THREAD

**Issue by jimmychu0807** [electric-capital/crypto-ecosystems#196]
Hi Electric Capital team,

First of all, thank you for writing the great developer report on all web3 ecosystems. It is great to know the ecosystem dev activities and their growth.

I am one of the Parity developers and would like to ask the EC team to consider merging developer activity count of Polkadot and Kusama ecosystem together. Currently when it comes to counting polkadot ecosystem active developers, "polkadot" ecosystem and "kusama" ecosystem are separated, with ~1400 and ~300 respectively, details refer to p64 (Polkadot) and p67 (Kusama) of [the report](https://github.com/electric-capital/developer-reports/blob/master/dev_report_2021.pdf). 

As mentioned in [our documentations](https://wiki.polkadot.network/docs/learn-kusama-vs-polkadot#use-cases), "Kusama was released as an early version of the same code to be used in Polkadot, which means they share the same underlying architecture". Kusama network serves as a "beta-net", but value-bearing. For ecosystem developers their launch process is usually `Testnet -> Kusama -> Polkadot`. So Kusama dev. acts. serve as "pre-"Polkadot dev. acts, and in this sense it would be more accurate to merge dev act counts together. 

Thanks for consideration.

cc @bjornwgnr @SuragSheth @SBalaguer

**Comment by jubos** [comment]
Thanks for the feedback.  Polkadot is a superset of Kusama, because Kusama is contained as a sub ecosystem of Polkadot, so we are already counting the activity as you expect.

**Comment by jimmychu0807** [comment]
Thank you @jubos

**Comment by helenajwang** [comment]
Hi Jimmy and Curtis, thanks for the effort on improving the github count of Polkadot/Kusama ecosystem. 

I had a good call with Maria and Ken and we agreed on having a data hand-over process for the github accounts from China activities such substrate hackathon, substrate course, substrate workshop and etc. We are going to propose a process internally and will circle back with you shortly.
