### ISSUE TITLE
Tag by language

### ISSUE THREAD

**Issue by benjyz** [electric-capital/crypto-ecosystems#20]
I did some research into what languages all the major unique blockchains are written in. It might make sense to add a language tag to projects

17 blockchains

C++ | 7
Go | 6
C# | 1
Haskell | 1
Java | 1
Ocaml | 1

**Comment by jubos** [comment]
hi @benjyz, it's an interesting idea.  I think it may be beyond the scope of this taxonomy as it is an inferred property that could change as the code in an underlying repo changes (e.g. someone starts with Javascript and moves to TypeScript over time).  As such it would be hard to keep in sync.  

Closing this issue for now.
