### ISSUE TITLE
Clean up some dfuse repository

### ISSUE THREAD

**Issue by maoueh** [electric-capital/crypto-ecosystems#22]
Hi there,

Thanks for listing up numbers of our repo our your taxonomy website, that's great. I would like to perform some clean up on the include repository list. Some of them are forked of other project we did to fix small bugs, so I think they should not be listed.

Before diving in this, I would like to better understand and should and should not be listed, so I can make a good clean up task. Sorry if the information is available already, was not able to find it.

Thanks again!

**Comment by jubos** [comment]
We keep forks and even small repos in because many teams contribute their own commits on top of forks for their own local bug fixes or changes in behavior they want.

Happy to add any other repos you think should be included.
