### ISSUE TITLE
Add SubWallet to Polkadot Ecosystem

### ISSUE THREAD

**Issue by hieudd** [electric-capital/crypto-ecosystems#264]
**SubWallet** is a user-friendly Web3 Multiverse Gateway for Polkadot and Kusama ecosystem. Our vision is to provide you with the simplest and most secure way to connect to blockchain-based applications like DeFi and GameFi on Polkadot.

### Where to find what:

1. To install the latest version of SubWallet, visit our [official website (open new window)](https://subwallet.app/).
2. For up-to-the-minute news on Polkadot, Kusama and SubWallet, follow our [Telegram](https://t.me/subwallet) & [Twitter](https://twitter.com/subwalletapp).
3. For help using SubWallet, jump into [Support Channel on Discord](https://discord.gg/EkFNgaBwpy).
4. To learn how to contribute to the SubWallet project, visit our community in [Discord](https://discord.gg/RFDpcG6xZ4).
5. To keep up with SubWallet's updates

### Why

1. SubWallet is built on top of Polkadot {.js} and focuses on improving user experience in the Polkadot and Kusama ecosystem—that is, we strive to make it easier for users to access and interact with Web3 applications that run on the Substrate Framework. In other words, we base SubWallet on Polkadot {.js}'s security backbone while improving all of its current drawbacks, including but not limited to:
2. Cumbersome infrastructure
3. Complicated user interface 
4. High latency  
5. This does not mean that we deny the contribution of Polkadot {.js}. It sets a crucial stepping stone for developers and plays a vital role for the Polkadot and Kusama ecosystem owing to its decentralization properties. Since there are too many blockchains and projects on the ecosystem that need to be managed, keeping track is immensely challenging for developers without a massive application like Polkadot {.js}. However, Polkadot end-users don't need this; they need something faster and more user-friendly. That's why SubWallet was born.
6. In the long run, we still believe that in the ecosystem, Polkadot {.js} is a pivotal platform application for developers. Our mission is to harness its power and bring it closer to the wider Polkadot community through user-friendly applications like SubWallet. 

### How

1. Below are our main features, or how we have improved from Polkadot {.js}: 
2. Monitor multi-chain assets on extension window
3. Send and receive assets with a few simple taps
4. Grant access and verify transactions to Web3
5. Manage and transfer NFT assets
6. Manage portfolio
7. And many more soon

https://www.youtube.com/watch?v=70tAQFn3BOk

**Comment by jubos** [comment]
This has been merged.  Thank you.
