### ISSUE TITLE
Add "archived" boolean attribute on old repositories

### ISSUE THREAD

**Issue by jubos** [electric-capital/crypto-ecosystems#268]
Some repositories get removed or archived, so add a special attribute on those entries in the toml to reflect that.

**Comment by neosavvy** [comment]
Thanks for having a look, let me know if you want me to submit a Python CLI that helps you check everything in the repo and write your tag/attribute back. Happy to add it to my list as it'll benefit me and anyone using this index.

**Comment by jubos** [comment]
This is called "missing" now since archived implies something different on github.
