### ISSUE TITLE
Update electric-capital.github.io to new commit. 

### ISSUE THREAD

**Issue by gfox1** [electric-capital/crypto-ecosystems#318]
Hi there,

Is someone able to update the [Electric Capital Crypto Systems](https://electric-capital.github.io/) site to a more recent commit? 

The site only displays projects from a commit dated to 2021-12-29. This commit is almost a year old and a lot more projects have been added to the repository that are not easily searchable by the public. 

Thanks. 

![image](https://user-images.githubusercontent.com/82609877/203629630-7e7b6e4e-ace9-4159-bea0-52c6e3a56812.png)

**Comment by jubos** [comment]
Good call!  This is updated to through 11/22 now.

**Comment by gfox1** [comment]
Amazing, thanks @jubos!

**Comment by APrimaveraV** [comment]
Hi again from Dominican Republic guys.👋🏽🇩🇴
