### ISSUE TITLE
Gaming with Chia

### ISSUE THREAD

**Issue by weaklysubjective** [electric-capital/crypto-ecosystems#399]
Please add this repo. Thanks
twitter : @givepeaceaplot1
https://github.com/weaklysubjective/MojoHunter

**Comment by weaklysubjective** [comment]
Hi there - i followed Gene's tweet to provide my app's link. Nothing has happened for a week now. Could you reply to this and let me know if there is an issue why you are not processing this PR. If this is not compliant with an open source project, please let me know and I can close it.

**Comment by jubos** [comment]
Thanks, we will get it merged.

**Comment by weaklysubjective** [comment]
Thanks !

**Comment by jubos** [comment]
@weaklysubjective, this repo doesn't exist anymore.  Please open up a PR when you want to add it back.
