### ISSUE TITLE
sub_ecosystems criteria 

### ISSUE THREAD

**Issue by GiupiDeLuca** [electric-capital/crypto-ecosystems#436]
What is the criteria for which a project is included as "sub_ecosystem" of another project? Is it correct to include all third party projects of a said ecosystem? (e.g. dapps, oracles, tools, L2's, etc..)

Are only open source projects accepted, or is there any other criteria?

**Comment by glasgowm148** [comment]
Unclear to me also, but for usefulness' sake, I'd assume it'd be only for established protocols launched on top (ie, LINK on ETH).

**Comment by eherrerosj** [comment]
It has changed a bit over time so please [refer to v1.1 for an explanation](https://github.com/electric-capital/crypto-ecosystems/releases/tag/1.1) and let me know if it's still not clear

**Comment by my-Gem** [comment]
How do I submit a developer PR? This is my github project URL - https://github.com/my-Gem/nftCairo

**Comment by eherrerosj** [comment]
> How do I submit a developer PR? This is my github project URL - https://github.com/my-Gem/nftCairo

you need to modify the corresponding ecosystem (toml file) and add your repo url to the list of repo URLs in the file

**Comment by my-Gem** [comment]
Could you please help me add it?

**Comment by my-Gem** [comment]
I have added your repo url to the list of repo URLs in the file, but ecosystem is not displayed?

**Comment by jubos** [comment]
Closing this out as this can be done in the PR.
