### ISSUE TITLE
Track GitLab repositories and organizations

### ISSUE THREAD

**Issue by arterialist** [electric-capital/crypto-ecosystems#464]
I have all repositories of my project on GitLab, and I guess some developers/founders do that as well. GitLab is better in some aspects and it would be easier to add it to the list than to migrate the whole infrastructure.

**Comment by eherrerosj** [comment]
> I have all repositories of my project on GitLab, and I guess some developers/founders do that as well. GitLab is better in some aspects and it would be easier to add it to the list than to migrate the whole infrastructure.

We also accept GitLab links. Feel free to open a PR with them
