### ISSUE TITLE
Not seeing all repos on https://electric-capital.github.io/ecosystem/celo

### ISSUE THREAD

**Issue by critesjosh** [electric-capital/crypto-ecosystems#68]
I am looking for the Celo gitcoin [repo](https://github.com/celo-org/gitcoin) on the [web repo explorer](https://electric-capital.github.io/ecosystem/celo), but it doesn't show up. 

It is listed in the database [here](https://github.com/electric-capital/crypto-ecosystems/blob/502529f606b0880c9ec84a6640713e02cdcd0249/data/ecosystems/c/celo.toml#L192).

Am I missing something?

**Comment by jubos** [comment]
Going to do an update to it in the coming days with all the of new repos recently added.
