### ISSUE TITLE
Help map out the crypto developer ecosystem! (1/17)

### ISSUE THREAD

**Issue by mariashen** [electric-capital/crypto-ecosystems#82]
Instructions:

You will be given a list of 100 open source repositories.

1. Find the GitHub organization to which these repositories belong.
2. Find the Ecosystem this repository belongs to (Bitcoin, Ethereum, etc.).
3. Find the Twitter, Discord, or Telegram associated with this repository, if any.

This is 1 of 17 assignments. We pay $20 per assignment. If you would like to continue with more assignments, just accept more Gitcoin bounties on this!

Assignment link: https://docs.google.com/spreadsheets/d/108pckfkua4rfdbEVOdt8XjeMHOLqwMZkJnWqF-0u5cw/edit?usp=sharing
Make a copy of the spreadsheet and make your changes in there, then share the link back to us once completed.

**Comment by mariashen** [comment]
I'm going to increase this bounty to $40, just FYI.

**Comment by justchen1369** [comment]
https://docs.google.com/spreadsheets/d/1dnb58wTI91aA8TmckRYc9Y2fYA6PaxtKSaGYd1_Y84I/edit

**Comment by saiy2k** [comment]
@mariashen  Is this still OPEN?
Shall I start the work through https://gitcoin.co/issue/electric-capital/crypto-ecosystems/82/100026740 ?
